Universe = vanilla
executable = /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/ISSBor.sh
request_memory = 4800MB 
output = /afs/cern.ch/work/z/zixuan/logISS/output_$(Cluster).$(Process)
error = /afs/cern.ch/work/z/zixuan/logISS/output_$(Cluster).$(Process)
log = /afs/cern.ch/work/z/zixuan/logISS/log_$(Cluster)
+AMSPublic = True
+JobFlavour = "workday"
transfer_output_files = ""

queue arguments from /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/joblist/list_jobs_mit.txt