Universe  = vanilla
executable  = /afs/cern.ch/work/z/zuhao/public/yanzx/isotpes_code/submit/MCO16.sh
output      = /afs/cern.ch/work/z/zuhao/public/yanzx/logMC/output_$(Cluster).$(Process)
error       = /afs/cern.ch/work/z/zuhao/public/yanzx/logMC/output_$(Cluster).$(Process)
log         = /afs/cern.ch/work/z/zuhao/public/yanzx/logMC/log_$(Cluster)
+AMSPublic = True
+JobFlavour = "espresso"
transfer_output_files = ""
queue arguments from /afs/cern.ch/work/z/zuhao/public/yanzx/isotpes_code/submit/joblist/list_MC_O16.txt
