Universe  = vanilla
executable  = /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/MCO16.sh
output      = /afs/cern.ch/user/z/zixuan/public/logMC/output_$(Cluster).$(Process)
error       = /afs/cern.ch/user/z/zixuan/public/logMC/output_$(Cluster).$(Process)
log         = /afs/cern.ch/user/z/zixuan/public/logMC/log_$(Cluster)
+AMSPublic = True
+JobFlavour = "espresso"
transfer_output_files = ""
queue arguments from /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/joblist/list_MC_O16.txt
