Universe  = vanilla
executable  = /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/ISSBer.sh
output      = /afs/cern.ch/work/z/zixuan/logISS/output_$(Cluster).$(Process)
error       = /afs/cern.ch/work/z/zixuan/logISS/output_$(Cluster).$(Process)
log         = /afs/cern.ch/work/z/zixuan/logISS/log_$(Cluster)
+AMSPublic = True
+JobFlavour = "workday"
transfer_output_files = ""

request_cpus = 1

queue arguments from /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/joblist/list_jobs_mit.txt



