Universe  = vanilla
executable  = /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/ISSBor.sh
output      = /afs/cern.ch/user/z/zixuan/public/logISS/output_$(Cluster).$(Process)
error       = /afs/cern.ch/user/z/zixuan/public/logISS/output_$(Cluster).$(Process)
log         = /afs/cern.ch/user/z/zixuan/public/logISS/log_$(Cluster)
+AMSPublic = True
+JobFlavour = "workday"
transfer_output_files = ""

queue arguments from /afs/cern.ch/user/z/zixuan/public/AMSIsotopeFramework/submit/joblist/list_jobs_yzx.txt



