analysis_target: "Beryllium"
input_files:
  - "root://eosams.cern.ch//eos/ams/user/z/zuhao/yanzx/ams_data/amsd69n_IHEPQcutDST/1305853512_10.root"
output_file: "/eos/user/z/zixuan/1305853512_10_testresults.root"