# Analysis Framework Configuration Version 1.3
# 根据旧代码库中 submit/joblist/ 的真实文件列表，彻底修正了所有MC样本的路径。

run_settings:
  # 定义本次运行的目标粒子，程序会从 PhysicsConstants.cpp 中查找它的属性
  target_nucleus: "Beryllium"
  
  # 定义每个任务处理的最大事件数 (-1 代表全部)
  max_events: 1000000

# 定义本次运行使用的物理模型和重建算法的版本组合
analysis_chain:
  chain_id: "GBLv6_TOFv1_IHEPQv2" # 用于标识分析链的短名称
  rigidity_version: "GBL_v6_InnerSpan"
  velocity_version: "TOF_BetaH_v1"
  cut_version:      "IHEPQ_v2"

# 定义这个配置文件所知道的所有数据样本
# 脚本会根据运行模式 (--mode) 选择正确的路径
samples_to_process:
  - name: "ISS_Beryllium"
    type: "ISS"
    # condor 模式使用硬编码的官方路径
    condor_path_pattern: "/eos/ams/user/z/zuhao/yanzx/ams_data/amsd69n_IHEPQcutDST/*.root"
    # local 模式使用单个文件用于快速测试
    local_path_pattern: "/eos/ams/user/z/zuhao/yanzx/ams_data/amsd69n_IHEPQcutDST/1627515134_10.root"
      
  - name: "MC_Be7"
    type: "MC"
    # 修正后的 condor 路径
    condor_path_pattern: "/eos/ams/group/mit/amsd69n_Be7MCB1308l1_4_8000605N0/*.root"
    # 修正后的 local 测试文件
    local_path_pattern: "/eos/ams/user/z/zuhao/yanzx/ams_data/amsd69n_IHEPQcutDST/16275*.root"

  - name: "MC_Be9"
    type: "MC"
    # 修正后的 condor 路径
    condor_path_pattern: "/eos/ams/group/mit/amsd69n_Be9MCB1308l1_4_8000605N0/*.root"
    # 修正后的 local 测试文件
    local_path_pattern: "/eos/ams/group/mit/amsd69n_Be9MCB1308l1_4_8000605N0/1686706136_5.root"

  - name: "MC_Be10"
    type: "MC"
    # 修正后的 condor 路径
    condor_path_pattern: "/eos/ams/group/mit/amsd69n_Be10MCB1308l1_4_8000605N0/*.root"
    # 修正后的 local 测试文件
    local_path_pattern: "/eos/ams/group/mit/amsd69n_Be10MCB1308l1_4_8000605N0/1686700365_5.root"

# Histogram definitions.
histograms:
  - name: "ISS_ID_H1"
    type: "TH1D"
    title: "Event counts of each isotope vs Ek/n"
    category: "per_isotope_ek_bin"

  - name: "ISS_ID_H2"
    type: "TH2D"
    title: "1/M of each isotope vs Ek/n"
    category: "per_isotope_ek_bin"
    nbinsx: 200
    xlow: 0.0
    xup: 0.5

  - name: "Event_Count_Total"
    type: "TH1D"
    title: "Total Processed Event Count"
    category: "default"
    nbins: 1
    low: 0.5
    up: 1.5