# Analysis Framework Configuration Version 1.0
# This file controls high-level settings and versioning.
# The framework provides default physics constants and binning;
# this file can be used to switch between different analysis chains or parameters.

# General settings
run_settings:
  target_nucleus: "Beryllium"
  output_file: "results.root"
  # Number of events to process. Set to -1 for all events.
  max_events: 100000000

# Histogram definitions
# The framework intelligently handles creation based on the 'category'.
# - category: "per_isotope_ek_bin"
#   - The histogram will be created for EACH isotope of the target_nucleus.
#   - The Y-axis (for TH2D) or X-axis (for TH1D) will use the isotope's
#     dedicated Ek/n binning, derived automatically from the default rigidity bins.
#   - The name will be automatically appended with "_IsotopeName" (e.g., "_Be7").
# - category: "default" (or if omitted)
#   - A single histogram is created with the specified name and binning.
#
histograms:
  - name: "ISS_ID_H1"
    type: "TH1D"
    title: "Event counts of each isotope vs Ek/n"
    category: "per_isotope_ek_bin"

  - name: "ISS_ID_H2"
    type: "TH2D"
    title: "1/M of each isotope vs Ek/n"
    category: "per_isotope_ek_bin"
    nbinsx: 200
    xlow: 0.0
    xup: 0.5

  - name: "Event_Count_Total"
    type: "TH1D"
    title: "Total Processed Event Count"
    category: "default"
    nbins: 1
    low: 0.5
    up: 1.5